import js from "@eslint/js";
import tseslint from "typescript-eslint";
import prettier from "eslint-config-prettier";
import globals from "globals";

export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      "**/build/**",
      "**/.turbo/**",
      "**/.wrangler/**",
      "**/coverage/**",
      "**/node_modules/**",
      "**/worker-configuration.d.ts",
      // Generated by @tanstack/router-plugin. Its own header asks to be excluded from
      // linters and formatters; it is already in .prettierignore. Without this, eslint --fix
      // rewrites it and the next codegen throws the change away.
      "apps/web/src/route-tree.gen.ts",
      // One-off dev utility scripts — not a workspace package, so no tsconfig
      // project service entry. ESLint option B: exclude cleanly rather than
      // add a bespoke tsconfig+allowDefaultProject entry for a single file.
      "scripts/**",
      // Workflow helper scripts — plain .mjs with no tsconfig project entry, same reasoning
      // as scripts/** above. Correctness is covered by unit tests in packages/repo-guards.
      ".github/scripts/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      globals: { ...globals.node },
      parserOptions: {
        projectService: {
          // Only genuinely one-off files live here now — each is a single file, not a
          // directory pattern, so there is no "depth" for a refactor to break. Test files
          // used to be enumerated here too, one directory depth at a time; see the
          // `**/*.test.ts` project block below for why they moved out.
          allowDefaultProject: [
            "packages/*/vitest.config.ts",
            "apps/*/vitest.config.ts",
            "apps/builds-api/worker-configuration.d.ts",
            // Standalone image-generation scripts, run via tsx, not part of the package's
            // own tsconfig.json build graph.
            "packages/og/scripts/*.tsx",
          ],
          defaultProject: "packages/ui/tsconfig.test.json",
          // Measured: 8 vitest.config.ts (one per package/app) + worker-configuration.d.ts
          // + 2 og scripts = 11. A little headroom for the next package's vitest.config.ts.
          maximumDefaultProjectFileMatchCount_THIS_WILL_SLOW_DOWN_LINTING: 12,
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "@typescript-eslint/consistent-type-imports": "error",
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
  // Test files get their type info from each package's own tsconfig.test.json instead of
  // the shared default project above. This used to be ~25 `allowDefaultProject` globs
  // enumerating exact directory depths per package (`features/*/*.test.ts`,
  // `features/*/*/*.test.ts`, ...) — a refactor that moved a test one level deeper fell
  // through every one of them and failed with an opaque "was not found by the project
  // service" error. Every tsconfig.test.json below `include`s its package with `src/**/*`,
  // a globstar, so nesting depth can no longer break this (same reasoning as the
  // per-package tsconfig.json requirement in the root CLAUDE.md, applied to tests).
  //
  // This can't be done as another `projectService.allowDefaultProject` entry pointing at a
  // per-package `defaultProject`, because `defaultProject` is a single global value:
  // typescript-eslint creates one project-service singleton for the whole `eslint` process,
  // seeded from whichever config block's `projectService` options are seen first, and every
  // later block's `projectService` options are silently ignored (see `populateProjectService`
  // in `@typescript-eslint/typescript-estree`'s `createParseSettings.js`). The classic
  // `parserOptions.project` array does not have that limitation — it resolves each file
  // against a real list of projects — so it's used here, scoped to test files only.
  // `packages/repo-guards/tsconfig.json` reuses its package's main tsconfig, since that one
  // never excluded `**/*.test.ts` in the first place.
  {
    files: ["**/*.test.ts", "**/*.test.tsx"],
    languageOptions: {
      parserOptions: {
        projectService: false,
        project: [
          "apps/builds-api/tsconfig.test.json",
          "apps/web/tsconfig.test.json",
          "packages/ballistics/tsconfig.test.json",
          "packages/og/tsconfig.test.json",
          "packages/optimizer/tsconfig.test.json",
          "packages/repo-guards/tsconfig.json",
          "packages/tarkov-data/tsconfig.test.json",
          "packages/ui/tsconfig.test.json",
        ],
      },
    },
  },
  // Disable type-checked rules for non-TypeScript files (e.g. eslint.config.js itself)
  // so that files outside any tsconfig project are not erroneously linted with type info.
  {
    files: ["**/*.js", "**/*.mjs", "**/*.cjs"],
    ...tseslint.configs.disableTypeChecked,
  },
  prettier,
);
