/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmokeRouteImport } from './routes/smoke'
import { Route as SimRouteImport } from './routes/sim'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as DataRouteImport } from './routes/data'
import { Route as CalcRouteImport } from './routes/calc'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as AecRouteImport } from './routes/aec'
import { Route as AdcRouteImport } from './routes/adc'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuilderIdRouteImport } from './routes/builder.$id'

const SmokeRoute = SmokeRouteImport.update({
  id: '/smoke',
  path: '/smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const SimRoute = SimRouteImport.update({
  id: '/sim',
  path: '/sim',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const CalcRoute = CalcRouteImport.update({
  id: '/calc',
  path: '/calc',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AecRoute = AecRouteImport.update({
  id: '/aec',
  path: '/aec',
  getParentRoute: () => rootRouteImport,
} as any)
const AdcRoute = AdcRouteImport.update({
  id: '/adc',
  path: '/adc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderIdRoute = BuilderIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BuilderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adc': typeof AdcRoute
  '/aec': typeof AecRoute
  '/builder': typeof BuilderRouteWithChildren
  '/calc': typeof CalcRoute
  '/data': typeof DataRoute
  '/matrix': typeof MatrixRoute
  '/sim': typeof SimRoute
  '/smoke': typeof SmokeRoute
  '/builder/$id': typeof BuilderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adc': typeof AdcRoute
  '/aec': typeof AecRoute
  '/builder': typeof BuilderRouteWithChildren
  '/calc': typeof CalcRoute
  '/data': typeof DataRoute
  '/matrix': typeof MatrixRoute
  '/sim': typeof SimRoute
  '/smoke': typeof SmokeRoute
  '/builder/$id': typeof BuilderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adc': typeof AdcRoute
  '/aec': typeof AecRoute
  '/builder': typeof BuilderRouteWithChildren
  '/calc': typeof CalcRoute
  '/data': typeof DataRoute
  '/matrix': typeof MatrixRoute
  '/sim': typeof SimRoute
  '/smoke': typeof SmokeRoute
  '/builder/$id': typeof BuilderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adc'
    | '/aec'
    | '/builder'
    | '/calc'
    | '/data'
    | '/matrix'
    | '/sim'
    | '/smoke'
    | '/builder/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adc'
    | '/aec'
    | '/builder'
    | '/calc'
    | '/data'
    | '/matrix'
    | '/sim'
    | '/smoke'
    | '/builder/$id'
  id:
    | '__root__'
    | '/'
    | '/adc'
    | '/aec'
    | '/builder'
    | '/calc'
    | '/data'
    | '/matrix'
    | '/sim'
    | '/smoke'
    | '/builder/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdcRoute: typeof AdcRoute
  AecRoute: typeof AecRoute
  BuilderRoute: typeof BuilderRouteWithChildren
  CalcRoute: typeof CalcRoute
  DataRoute: typeof DataRoute
  MatrixRoute: typeof MatrixRoute
  SimRoute: typeof SimRoute
  SmokeRoute: typeof SmokeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/smoke': {
      id: '/smoke'
      path: '/smoke'
      fullPath: '/smoke'
      preLoaderRoute: typeof SmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sim': {
      id: '/sim'
      path: '/sim'
      fullPath: '/sim'
      preLoaderRoute: typeof SimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calc': {
      id: '/calc'
      path: '/calc'
      fullPath: '/calc'
      preLoaderRoute: typeof CalcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aec': {
      id: '/aec'
      path: '/aec'
      fullPath: '/aec'
      preLoaderRoute: typeof AecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adc': {
      id: '/adc'
      path: '/adc'
      fullPath: '/adc'
      preLoaderRoute: typeof AdcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/$id': {
      id: '/builder/$id'
      path: '/$id'
      fullPath: '/builder/$id'
      preLoaderRoute: typeof BuilderIdRouteImport
      parentRoute: typeof BuilderRoute
    }
  }
}

interface BuilderRouteChildren {
  BuilderIdRoute: typeof BuilderIdRoute
}

const BuilderRouteChildren: BuilderRouteChildren = {
  BuilderIdRoute: BuilderIdRoute,
}

const BuilderRouteWithChildren =
  BuilderRoute._addFileChildren(BuilderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdcRoute: AdcRoute,
  AecRoute: AecRoute,
  BuilderRoute: BuilderRouteWithChildren,
  CalcRoute: CalcRoute,
  DataRoute: DataRoute,
  MatrixRoute: MatrixRoute,
  SimRoute: SimRoute,
  SmokeRoute: SmokeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
