import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const scriptsDir = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(scriptsDir, "..");

interface Asset {
  label: string;
  varName: string;
  path: string;
}

const ASSETS: Asset[] = [
  { label: "Bungee 400", varName: "BUNGEE_400_B64", path: "fonts/Bungee-Regular.ttf" },
  { label: "Chivo 700", varName: "CHIVO_700_B64", path: "fonts/Chivo-700.ttf" },
  { label: "Azeret Mono 500", varName: "AZERET_MONO_500_B64", path: "fonts/AzeretMono-500.ttf" },
  { label: "Azeret Mono 700", varName: "AZERET_MONO_700_B64", path: "fonts/AzeretMono-700.ttf" },
  { label: "Fallback card", varName: "FALLBACK_CARD_B64", path: "assets/fallback-card.png" },
];

function emit(): string {
  const lines: string[] = [
    "// AUTO-GENERATED by `pnpm --filter @tarkov/og run build:embedded`.",
    "// Do not edit by hand. Re-run the script after changing any font or fallback PNG.",
    "",
  ];
  for (const a of ASSETS) {
    const abs = resolve(pkgRoot, a.path);
    const bytes = readFileSync(abs);
    const b64 = bytes.toString("base64");
    lines.push(`// ${a.label} — ${bytes.byteLength} bytes (${b64.length} b64 chars)`);
    lines.push(`export const ${a.varName} = ${JSON.stringify(b64)};`);
    lines.push("");
  }
  return lines.join("\n");
}

function main(): void {
  const out = resolve(pkgRoot, "src/embedded.ts");
  writeFileSync(out, emit());
  console.log(`wrote ${out}`);
}

main();
