import { defineConfig } from "vitest/config";

/* Thresholds are a RATCHET, not an aspiration. They are set to the coverage this
 * package actually had when enforcement was switched on (see
 * docs/plans/2026-08-19-pre-refactor-hardening-plan.md for the measured baseline table).
 *
 * Raise them as tests land. NEVER lower one to make CI pass — if a change drops
 * coverage, the change needs tests, not a smaller number. */
export default defineConfig({
  test: {
    include: ["src/**/*.test.ts", "src/**/*.test.tsx"],
    coverage: {
      provider: "v8",
      include: ["src/**/*.ts", "src/**/*.tsx"],
      exclude: [
        "src/**/*.test.ts",
        "src/**/*.test.tsx",
        "src/__fixtures__/**",
        "src/index.ts",
        "src/view-model.ts",
        // Generated build artifacts, not hand-written source — `embedded.ts` is a
        // 377,000-char file of base64 font/PNG string constants produced by
        // `scripts/generate-embedded.tsx`, and `embedded-fonts.ts` only decodes and
        // memoizes those constants for `pair-card.tsx`'s fallback-PNG path. Testing
        // generated output would mean asserting on this run's own regenerated bytes —
        // not a behavioral contract, just a tautology. Locked in
        // docs/plans/2026-08-19-pre-refactor-hardening-plan.md's Stage 1.3 decision.
        "src/embedded.ts",
        "src/embedded-fonts.ts",
      ],
      thresholds: {
        lines: 95,
        functions: 95,
        branches: 85,
        statements: 95,
      },
    },
  },
});
